const provinces_data = {
    province: [
        
        { id: "0",
        housename: "Aceh",
        provincename: "Aceh",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Rumoh_Cut_Nyak_Dhi%C3%ABn.jpg/1280px-Rumoh_Cut_Nyak_Dhi%C3%ABn.jpg",
        video: "https://www.youtube.com/watch?v=HUchNTuSOWY",
        description: "Rumoh Aceh adalah sebutan bagi orang Aceh yang berarti Rumah Aceh. Salah satu rumah adat di Aceh ini yaitu rumah Krong Bade. Konsep dari bangunan ini yaitu memakai konsep rumah panggung, yang tingginya mencapai 2 sampai 3 meter. Lalu hampir seluruh material bangunannya memakai bahan alami, yaitu berbagai jenis kayu yang kokoh. Lalu untuk atapnya banyak memakai daun Rumbia. Pada kolong rumah panggung, pemilik rumah biasa menyimpan bahan makanan di sana. Lalu kegiatan masyarakat terutama wanita biasanya melakukan kegiatan menenun di bawah rumahnya.",
        link: "https://id.wikipedia.org/wiki/Rumah_adat_Aceh"},

        { id: "1",
        housename: "Bolon",
        provincename: "Sumatera Utara",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Rumah_Bolon_%28Batak_Traditional_House%29.jpg/1920px-Rumah_Bolon_%28Batak_Traditional_House%29.jpg",
        video: "https://www.youtube.com/watch?v=Zv-P9cVbbu0",
        description: "Rumah Bolon adalah rumah adat suku Batak Toba. Rumah ini berbentuk panggung dengan bahan utama bangunan yaitu berupa kayu. Hal unik dari rumah Bolon ini terletak di bentuk atapnya yang melengkung dan runcing di tiap ujungnya.",
        link: "https://id.wikipedia.org/wiki/Ruma_Bolon"},

        { id: "2",
        housename: "Gadang",
        provincename: "Sumatera Barat",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Rumah_Gadang.jpg/1280px-Rumah_Gadang.jpg",
        video: "https://www.youtube.com/watch?v=zmV-njPlxxA",
        description: "Rumah Gadang adalah rumah adat dari suku Minangkabau. Dilihat dari bentuknya rumah adat ini bisa disebut juga rumah bagonjong, karena bentuk atapnya yang bergonjong runcing menjulang.",
        link: "https://id.wikipedia.org/wiki/Rumah_Gadang"},

        { id: "3",
        housename: "Selaso Jatuh Kembar",
        provincename: "Riau",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Rumah_Adat_Balai_Selasar_Jatuh_Tunggal%2C_Rumah_Adat_Riau_di_Taman_Mini_Indonesia_Indah.jpg/1280px-Rumah_Adat_Balai_Selasar_Jatuh_Tunggal%2C_Rumah_Adat_Riau_di_Taman_Mini_Indonesia_Indah.jpg",
        video: "https://www.youtube.com/watch?v=qB0MsxffD-c",
        description: "Rumah Jatuah Kambar atau bisa juga disebut Selaso Jatuh Kembar merupakan rumah adat Khas Riau yang berupa Balai Selaso Jatuh. Rumah adat ini biasanya tidak dipakai untuk rumah tinggal, tetapi rumah adat ini biasanya dipakai sebagai tempat kegiatan masyarakat, yang biasa disebut juga balai penobatan, balirung sari, balai kerapatan dan masih banyak lagi.",
        link: "https://id.wikipedia.org/wiki/Rumah_adat_Selaso_Jatuh_Kembar"},

        { id: "4",
        housename: "Belah Bubung",
        provincename: "Kepulauan Riau",
        img: "https://asset.kompas.com/crops/jQ7tBh8Ogd9G5I7rWm2s010Tcf4=/169x39:870x507/750x500/data/photo/2021/05/04/609140fe1c291.png",
        video: "https://www.youtube.com/watch?v=eXF-ki1jfIQ",
        description: "Rumah Belah Bubung adalah rumah adat dari Kepulauan Riau. Rumah Belah Bubung juga bisa disebut sebagai rumah Rubung atau rumah Bubung Melayu. Menurut Kepercayaan dari masyarakat, nama Rumah Belah Bubung ini diberikan oleh orang asing yang datang ke Indonesia seperti Belanda dan Tiongkok. Rumah Belah Bubung ini memiliki model rumah yang sama seperti rumah panggung. Arsitektur rumah ini memiliki tinggi 2 meter dari tanah dan ditopang oleh beberapa tiang penyangga. Atap rumah ini juga berbentuk seperti pelana kuda.",
        link: "https://id.wikipedia.org/wiki/Rumah_Belah_Bubung"},

        { id: "5",
        housename: "Kajang Lako",
        provincename: "Jambi",
        img: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Rmh_Tuo_Tbr.jpg",
        video: "https://www.youtube.com/watch?v=93B70i0s3Os",
        description: "Kajang Lako adalah rumah adat milik Suku Batin, Jambi. Rumah adat ini juga bisa disebut sebagai Rumah Tuo atau yang berarti Rumah Tua. Rumah adat ini tidak hanya dibangun untuk rumah tempat tinggal saja, teetapi rumah ini dibangun dengan memperhatikan fungsi sosial dan budaya masyarakat Jambi. Di daerah rumah ini juga biasanya dibangun lumbung untuk tempat menyimpan padi hasil panen masyarakat.",
        link: "https://id.wikipedia.org/wiki/Kajang_Lako"},

        { id: "6",
        housename: "Bubungan Lima",
        provincename: "Bengkulu",
        img: "https://o-cdn-cas.sirclocdn.com/parenting/images/rumah-adat-bengkulu_1.width-800.format-webp.webp",
        video: "https://www.youtube.com/watch?v=Y6H9xzd9y58",
        description: "Rumah Bubungan Lima adalah rumah adat dari provinsi Bengkulu. Rumah ini memiliki arstitektur seperti rumah panggung yang ditopang oleh beberapa tiang penopang. Rumah ini juga biasanya tidak dipakai untuk tempat tinggal, melainkan biasa digunakan untuk acara adat masyarakat bengkulu. Rumah adat ini dibangun oleh satu bahan material yaitu kayu yang memiliki kualitas bagus seperti kayu Medang Kemuning.",
        link: "https://id.wikipedia.org/wiki/Rumah_Bubungan_Lima"},

        { id: "7",
        housename: "Limas",
        provincename: "Sumatera Selatan",
        img: "https://wonderfulimage.s3-id-jkt-1.kilatstorage.id/1622118118-rumah_limas-2-medium.jpg",
        video: "https://www.youtube.com/watch?v=HYlSp4NsGR0",
        description: "Rumah Limas adalah rumah adat yang berasal dari provinsi Sumatera Selatan. Selain ditandai dengan atap yang berbentuk limas, rumah adat ini memiliki lantai bertingkat-tingkat yang biasa disebut dengan Bengkilas atau Kijing dan hanya dipergunakan untuk kepentingan masyarakat seperti hajatan. Kontruksi rumah adat ini berbentuk rumah panggung.",
        link: "https://id.wikipedia.org/wiki/Rumah_Limas"},

        { id: "8",
        housename: "Rakit",
        provincename: "Kepulauan Bangka Belitung",
        img: "https://asset.kompas.com/crops/yFFFcVRNB8VJRjB2R-j97xeHbf0=/34x0:589x370/750x500/data/photo/2021/05/04/609136a05d0df.png",
        video: "https://www.youtube.com/watch?v=SeyrtirHZuE",
        description: "Rumah Rakit ini adalah rumah adat yang berasal dari provinsi Kepulauan Bangka Belitung. Rumah Rakit ini adalah rumah tertua di provinsi Kepulauan Bangka Belitung, menurut sejarah diperkirakan rumah adat ini sudah ada sejak zaman kerajaan Sriwijaya. Rumah Rakit ini dibangun diatas rakit dan mengapung di sepanjang pinggiran sungai. Rumah Rakit ini akan diikatkan pada sebuah serdang atau dalam bahasa Indonesia penambat agar rumah rakit tidak hanyut terbawa arus sungai.",
        link: "https://id.wikipedia.org/wiki/Rumah_tradisional_Bangka"},

        { id: "9",
        housename: "Nuwo Sesat",
        provincename: "Lampung",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Rumah_adat_Nuwo_Sesat_lampung.jpg/1280px-Rumah_adat_Nuwo_Sesat_lampung.jpg",
        video: "https://www.youtube.com/watch?v=YapJaXFbcjA",
        description: "Nuwo Sesat adalah rumah adat yang berasal dari provinsi Lampung. Nuwo Sesat berfungsi sebagai tempat adat bagi para purwatin atau dalam bahasa Indonesia Penyimbang pada saat mengadakan pepung adat atau dalam bahasa Indonesia Musyawarah. Maka dari itu rumah adat ini biasa disebut juga dengan Balai Agung. Arsitektur rumah adat ini adalah rumah panggung dengan atap yang biasa disebut dengan Rurung Agung.",
        link: "https://id.wikipedia.org/wiki/Nuwo_sesat"},

        { id: "10",
        housename: "Sulah Nyanda",
        provincename: "Banten",
        img: "https://o-cdn-cas.sirclocdn.com/parenting/images/rumah-adat-banten_V82juev.width-800.format-webp.webp",
        video: "https://www.youtube.com/watch?v=PvmrcvlgYhU",
        description: "Sulah Nyanda adalah rumah adat suku Badui yang berasal dari provinsi Banten. Rumah adat ini disebut Sulah Nyanda karena atapnya yang terbuat dari daun nipah yang dikeringkan. Rumah adat Badui ini juga biasa disebut sebagai imah yang berarti rumah dalam bahasa Indonesia dan rumah harus menghadap ke arah selatan karena kepercayaan masyarakat Badui.",
        link: "https://id.wikipedia.org/wiki/Sulah_nyanda"},

        { id: "11",
        housename: "Kebaya",
        provincename: "DKI Jakarta",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Rumah_Adat_Kebaya_dari_Jakarta.jpg/1024px-Rumah_Adat_Kebaya_dari_Jakarta.jpg",
        video: "https://www.youtube.com/watch?v=mJMkrAf0RMM",
        description: "Rumah Kebaya merupakan rumah adat dari suku Betawi yang berasal dari DKI Jakarta. Ciri khas dari rumah adat ini adalah rumah ini memiliki teras yang luas yang berfungsi untuk menjamu tamu dan menjadi tempat bersantai pemilik rumah. Arsitektur rumah adat ini berbentuk rumah panggung seperti kebanyakan rumah adat lainnya.",
        link: "https://id.wikipedia.org/wiki/Rumah_kebaya"},

        { id: "12",
        housename: "Julang Ngapak",
        provincename: "Jawa Barat",
        img: "https://upload.wikimedia.org/wikipedia/commons/a/a0/COLLECTIE_TROPENMUSEUM_Huizen_in_Papandak_TMnr_60050402.jpg",
        video: "https://www.youtube.com/watch?v=Z6JF1I_Cpbg",
        description: "Julang Ngapak adalah salah satu jenis gaya bangunan rumah khas Sunda. Arti tersebut berasal dari kata Julang yang berarti burung dan Ngapak yang berarti mengepakkan (dalam bahasa Sunda). Ciri dari rumah adat ini yaitu bentuk atapnya yang melebar pada setiap sisi, dan pada bagian atasnya berbentuk huruf sehingga secara keseluruhannya rumah adat ini menyerupai burung yang sedang mengepakkan sayap.",
        link: "https://id.wikipedia.org/wiki/Rumah_tradisional_Sunda"},

        { id: "13",
        housename: "Joglo",
        provincename: "Jawa Tengah",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Joglo_Pencu%2C_Rumah_Tradisional_Kudus.jpg/1280px-Joglo_Pencu%2C_Rumah_Tradisional_Kudus.jpg",
        video: "https://www.youtube.com/watch?v=Tp2e1A6vNAo",
        description: "Rumah Adat Joglo merupakan rumah adat Jawa. Rumah adat ini berbbentuk persegi dengan empat tiang di tengahnya. Tiang disebut saka guru. Terdapat juga tiang untuk menopang. Bentuk Atap rumah joglo berbentuk seperti gunung. Rumah adat ini masih akan kita sering liat di daerah Kampung Kotagede.",
        link: "https://id.wikipedia.org/wiki/Joglo"},

        { id: "14",
        housename: "Joglo",
        provincename: "DI Yogyakarta",
        img: "https://cdnwpedutorenews.gramedia.net/wp-content/uploads/2021/10/21131102/Rumah-Joglo.png",
        video: "https://www.youtube.com/watch?v=Tp2e1A6vNAo",
        description: "Rumah Adat Joglo merupakan rumah adat Jawa. Rumah adat ini berbbentuk persegi dengan empat tiang di tengahnya. Tiang disebut saka guru. Terdapat juga tiang untuk menopang. Bentuk Atap rumah joglo berbentuk seperti gunung. Rumah adat ini masih akan kita sering liat di daerah Kampung Kotagede.",
        link: "https://id.wikipedia.org/wiki/Joglo"},

        { id: "15",
        housename: "Joglo",
        provincename: "Jawa Timur",
        img: "https://cdnwpedutorenews.gramedia.net/wp-content/uploads/2021/11/18194925/unnamed-22.png",
        video: "https://www.youtube.com/watch?v=Tp2e1A6vNAo",
        description: "Rumah Adat Joglo merupakan rumah adat Jawa. Rumah adat ini berbbentuk persegi dengan empat tiang di tengahnya. Tiang disebut saka guru. Terdapat juga tiang untuk menopang. Bentuk Atap rumah joglo berbentuk seperti gunung. Rumah adat ini masih akan kita sering liat di daerah Kampung Kotagede.",
        link: "https://id.wikipedia.org/wiki/Joglo"},

        { id: "16",
        housename: "Gapura Candi Bentar",
        provincename: "Bali",
        img: "https://s3.ap-southeast-1.wasabisys.com/c340968/2023/05/W2Rbt6Vb-Gapura-Candi-Bentar.webp",
        video: "https://www.youtube.com/watch?v=T0bVDmm5yHU",
        description: "Gapura Candi Bentar merupakan rumah adat yang berasal dari provinsi Bali. Rumah Gapura Candi Bentar sejatinya merujuk pada bangunan gapura yang menjadi gerbang rumah-rumah adat Bali. Bentuk rumah adat ini merupakan gapura, atau candi yang terbelah dua tepat di tengah-tengahnya sehingga menjadi bentukan yang simetri.",
        link: "https://id.wikipedia.org/wiki/Rumah_Gapura_Candi_Bentar"},

        { id: "17",
        housename: "Bale Lumbung",
        provincename: "Nusa Tenggara Barat",
        img: "https://cdn.idntimes.com/content-images/community/2019/07/sade-00499abad3ffcce1a0ed53acd1e4269a.jpg",
        video: "https://www.youtube.com/watch?v=26nAfTRtmM0",
        description: "Bale Lumbung merupakan rumah adat yang berasal dari provinsi Nusa Tenggara Barat. Rumah adat ini merupakan rumah asli dari masyarakat suku Sasak yang merupakan penduduk aslli Pulau Lombok. Rumah Bale Lumbung ini memiliki 2 jenis rumah adat juga. Bale yang biasa dipakai masyarakat suku Sasak sebagai tempat tinggal, sedagnkan Lumbung merupakan tempat untuk menyimpan hasil panen seperti padi dan segala kebutuhan yang lainnya. Kata Lumbung ini memiliki arti dalam bahasa Indonesia yang berarti tempat penyimpanan hasil panen.",
        link: "https://id.wikipedia.org/wiki/Rumah_adat_Sasak"},

        { id: "18",
        housename: "Musalaki",
        provincename: "Nusa Tenggara Timur",
        img: "https://static.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/2023/07/05/Rumah-Musalaki-768x512-4291985126.jpg",
        video: "https://www.youtube.com/watch?v=LlWW-AEsfG4",
        description: "Rumah Musalaki yaitu rumah adat yang berasal dari provinsi Nusa Tenggara Timur. Rumah adat ini merupakan tempat tinggal khusus bagi kepala suku dari beberapa suku di provinsi Nusa Tenggara Timur. Karena Rumah Musalaki ini sudah menjadi lambang dari provinsi Nusa Tenggara Timur, bangunan-bangunan pemerintahan seperti kelurahan, kecamatan, hingga kabupaten menggunakan desai bangunan ini untuk membangun bangunannya.",
        link: "https://id.wikipedia.org/wiki/Rumah_musalaki"},

        { id: "19",
        housename: "Radakng",
        provincename: "Kalimantan Barat",
        img: "https://upload.wikimedia.org/wikipedia/id/5/5c/Rumah_radank.jpg",
        video: "https://www.youtube.com/watch?v=Xqfe0Xa02bc",
        description: "Rumah Radakng merupakan rumah adat bagi orang suku Dayak. Rumah adat Radakng ini disebut sebagai rumah adat paling besar yang ada di Indonesia. Dikatakan sebagai rumah adat terbesar, karena bangunannya memiliki panjang 138 meter dan tinggi 7 meter. Rumah adat ini biasa juga disebut sebagai rumah panjang karena bentuknya yang panjang. Arsitektur rumah adat ini juga menggunakan arsitektur rumah panggung seperti rumah adat yang lainnya",
        link: "https://id.wikipedia.org/wiki/Rumah_Radakng"},

        { id: "20",
        housename: "Betang",
        provincename: "Kalimantan Tengah",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Rumah_Betang_Sei_Pasah_180505002.JPG/1280px-Rumah_Betang_Sei_Pasah_180505002.JPG",
        video: "https://www.youtube.com/watch?v=JnEm2gcai0Q",
        description: "Rumah betang adalah rumah adat khas Kalimantan yang terdapat diberbagai penjuru Kalimantan dan dihuni oleh masyarakat Dayak terutama di daerah hulu sungai yang biasanya menjadi pusat permukiman suku Dayak. Rumah Betang dengan rumah Radakng dari segi bentuk dan ukurannya.",
        link: "https://id.wikipedia.org/wiki/Rumah_Betang"},

        { id: "21",
        housename: "Bubungan Tinggi",
        provincename: "Kalimantan Selatan",
        img: "https://upload.wikimedia.org/wikipedia/id/8/8e/Tampak_Samping_Bubungan_Tinggi_Teluk_Selong_Martapura.JPG",
        video: "https://www.youtube.com/watch?v=nK_fFSSTNOE",
        description: "Rumah Bubungan Tinggi rumah adat suku Banjar di Kalimantan Selatan dan bisa dibilang merupakan ikonnya Rumah Banjar karena jenis rumah inilah yang paling terkenal karena menjadi maskot rumah adat khas provinsi Kalimantan Selatan. Rumah ini disebut juga Rumah Baanjung karena memiliki dua anjungan pada kiri dan kanan.",
        link: "https://id.wikipedia.org/wiki/Bubungan_Tinggi"},

        { id: "22",
        housename: "Lamin",
        provincename: "Kalimantan Timur",
        img: "https://www.goodnewsfromindonesia.id/uploads/post/large-lamin-adat-pemung-tawai-samarinda-048581dea496c453b6b263ad127ba185.jpg",
        video: "https://www.youtube.com/watch?v=RpJpAfWd-Mw",
        description: "Rumah Lamin adalah rumah adat dari Kalimantan Timur. Rumah Lamin adalah identitas masyarakat Dayak di Kalimantan Timur. Rumah Lamin mempunyai panjang sekitar 300 meter, lebar 15 meter, dan tinggi kurang lebih 3 meter. Rumah Lamin juga dikenal sebagai rumah panggung yang panjang dari sambung menyambung. Rumah ini dapat ditinggal oleh beberapa keluarga karena ukuran rumah yang cukup besar. Salah satu rumah Lamin yang berada di Kalimantan Timur bahkan dihuni oleh 12 sampai 30 keluarga. Rumah Lamin dapat menampung kurang lebih 100 orang. Pada tahun 1967, rumah Lamin diresmikan oleh pemerintah Indonesia.",
        link: "https://id.wikipedia.org/wiki/Rumah_Lamin"},

        { id: "23",
        housename: "Baloy",
        provincename: "Kalimantan Utara",
        img: "https://upload.wikimedia.org/wikipedia/commons/c/c0/Baloy_Mayo_Adat_Tidung_%282%29.JPG",
        video: "https://www.youtube.com/watch?v=7BTjORJ7yq8",
        description: "Rumah adat terkenal dari masyarakat Kalimantan Utara disebut Rumah Baloy. Rumah adat ini merupakan hasil kebudayaan seni arsitektur dari masyarakat suku Tidung, Kalimantan Utara. Seperti suku lainnya, suku Tidung ini mempunyai kebudayaan dan model rumah adat sendiri. Walaupun rumah adat ini masih menggunakan sejumlah tiang tinggi pada bagian bawahnya, bentuk bangunan rumah adat ini terlihat lebih modern dan modis. Berdasarkan dugaan para peneliti, besar kemungkinan rumah adat ini adalah hasil pengembangan arsitektur Dayak dari Rumah Panjang (Rumah Lamin) seperti yang dihuni oleh suku Dayak Kenyah di Kalimantan Timur.",
        link: "https://id.wikipedia.org/wiki/Rumah_Baloy"},

        { id: "24",
        housename: "Walewangko",
        provincename: "Sulawesi Utara",
        img: "https://asset.kompas.com/crops/a8LHsc9dwHLQ2JB17tIVJJvAm9A=/0x5:700x356/750x500/data/photo/2021/01/22/600a755ece87c.jpg",
        video: "https://www.youtube.com/watch?v=iHdye44fSA8",
        description: "Rumah Pewaris atau Walewangko adalah rumah adat daerah Minahasa, Provinsi Sulawesi Utara. Minahasa dahulu dikenal dengan nama Tanah Malesung yang merupakan daerah Semenanjung tempat persinggahan Bangsa Portugis dan Spanyol. Oleh karena tanahnya yang subur, Bangsa Portugis dan Spanyol tertarik dengan daerah tersebut. Sementara itu, raja pertama Manado adalah keturunan Bangsa Spanyol, yaitu Muntu Untu. Dari raja pertama inilah diyakini masyarakat Minahasa mengenal rumah adat.",
        link: "https://id.wikipedia.org/wiki/Rumah_Pewaris"},

        { id: "25",
        housename: "Bantayo Poboide",
        provincename: "Gorontalo",
        img: "https://upload.wikimedia.org/wikipedia/id/0/06/Dulohupa.jpg",
        video: "https://www.youtube.com/watch?v=9Y1K8UY97Gw",
        description: "Bantayo Poboide dari namanya terdiri atas kata “bantayo” yang berarti bangsal, balai; dan “poboide” yang berarti berbicara. Bantayo Poboide merupakan bangsal atau balai untuk membicarakan berbagai persoalan tentang negeri yang terorganisir, kedudukannya di atas Maharaja, mempunyai kekuatan hukum, berdiri sendiri (independent), tidak terkait dengan politik, semata-mata bekerja untuk kesejahteraan negeri, dan membangun moralitas pemimpin dan rakyat negeri sesuai adat dan syara (hukum yang bersendi ajaran Islam).",
        link: "https://id.wikipedia.org/wiki/Bantayo_Poboide"},

        { id: "26",
        housename: "Tambi",
        provincename: "Sulawesi Tengah",
        img: "https://awsimages.detik.net.id/community/media/visual/2021/11/01/rumah-tambi.jpeg?w=1200",
        video: "https://www.youtube.com/watch?v=MpqSBxphS3U",
        description: "Rumah Tambi adalah rumah adat atau rumah tradisional dari Tampo Lore, Kabupaten Poso, provinsi Sulawesi Tengah, Indonesia. Rumah adat ini berbentuk panggung yang atapnya sekaligus berguna sebagai dinding. Rumah Tambi merupakan rumah bagi suku Pekurehua (Napu), Bada dan Behoa di Lemba Lore yang umumnya merupakan rumah penduduk setempat serta beberapa wilayah di Sulawesi Tengah menjadikan rumah ini sebagai rumah bagi kepala adat.",
        link: "https://id.wikipedia.org/wiki/Rumah_Tambi"},

        { id: "27",
        housename: "Boyang",
        provincename: "Sulawesi Barat",
        img: "https://awsimages.detik.net.id/community/media/visual/2022/09/17/rumah-adat-mandar_169.jpeg?w=1200",
        video: "https://www.youtube.com/watch?v=SoP8w_ok2IM",
        description: "Boyang merupakan rumah adat yang berasal dari Provinsi Sulawesi Barat. Rumah Boyang memiliki gaya arsitektur yang unik, berbentuk rumah panggung yang tersusun dari material kayu dan ditopang tiang-tiang penyangga. Rumah ini menjadi tempat tinggal Suku Mandar yang merupakan suku asli dari Sulawesi Barat.",
        link: "https://id.wikipedia.org/wiki/Rumah_Adat_Boyang"},

        { id: "28",
        housename: "Tongkonan",
        provincename: "Sulawesi Selatan",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Tongkonan_Toraja.jpg/1280px-Tongkonan_Toraja.jpg",
        video: "https://www.youtube.com/watch?v=P1eeC1hRYvQ",
        description: "Tongkonan adalah rumah adat masyarakat suku Toraja yang berada di Provinsi Sulawesi Selatan, Indonesia. Arsitektur tongkonan dikenal dengan bentuknya yang khas melalui struktur bawah, tengah dan atas yang memiliki keindahan estetika struktur dan konstruksinya. Tongkonan tidak lagi dijadikan rumah tempat tinggal tetapi sudah tidak dihuni lagi dikarenakan setiap keluarga yang mendiami Tongkonan pada umumnya telah membangun rumah tinggal sendiri.",
        link: "https://id.wikipedia.org/wiki/Tongkonan"},

        { id: "29",
        housename: "Banua Tada",
        provincename: "Sulawesi Tenggara",
        img: "https://cdn.rri.co.id/berita/58/1674525440-Rumah%20Banua%20Tada%2C%20Rumah%20Adat%20Provinsi%20Sulawesi%20Tenggara.JPG",
        video: "https://www.youtube.com/watch?v=iNhtCOHGORs",
        description: "Banua Tada adalah rumah adat yang berasal dari Provinsi Sulawesi Tenggara. Banua Tada merupakan rumah tempat tinggal Suku Wolio atau orang Buton di pulau Buton. Kata banua dalam bahasa setempat berarti rumah sedangkan kata tada berarti siku, sehingga banua tada dapat diartikan sebagai rumah siku. Hal ini karena struktur rangka bangunan terdiri dari siku-siku. Keunikan dari rumah banua tada adalah memiliki bentuk rumah panggung, tetapi pada pembangunannya tidak menggunakan satupun paku.",
        link: "https://id.wikipedia.org/wiki/Rumah_Adat_Banua_Tada"},

        { id: "30",
        housename: "Baileo",
        provincename: "Maluku",
        img: "https://asset.kompas.com/crops/sSTDVPrDnbprK5Pq4iItEyRBOyo=/0x61:696x525/750x500/data/photo/2022/02/06/61ff97a64a7d8.jpg",
        video: "https://www.youtube.com/watch?v=_dK6_8MHEFA",
        description: "Baileo adalah rumah adat Maluku. Baileo merupakan representasi kebudayaan Maluku dan memiliki fungsi yang sangat penting bagi kehidupan masyarakat. Baileo berfungsi sebagai tempat penyimpanan benda-benda suci, tempat upacara adat, sekaligus sebagai balai warga. Ciri utama baileo adalah ukurannya besar, dan memiliki bentuk yang berbeda jika dibandingkan dengan rumah-rumah lain di sekitarnya.",
        link: "https://id.wikipedia.org/wiki/Baileo"},

        { id: "31",
        housename: "Sasadu",
        provincename: "Maluku Utara",
        img: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Rumah_adat_Sasadu_Desa_Gamtala.jpg",
        video: "https://www.youtube.com/watch?v=cpv393ydOF",
        description: "Sasadu merupakan rumah adat suku bangsa Sahu di Halmahera Barat yang juga merupakan suku bangsa asli dan tertua yang ada di daerah tersebut. Di Halmahera Barat, rumah ini lazim ditemui di setiap desa. Penggunaan Sasadu sebagai lokasi pertemuan masyarakat biasanya terkait dengan diselenggarakannya berbagai acara, misalnya ritual atau upacara adat seperti perayaan panen dan pemilihan ketua adat, dan menyambut tamu yang datang. Meski demikian dapat pula Sasadu digunakan hanya untuk sekadar bersantai tanpa ada acara khusus.",
        link: "https://id.wikipedia.org/wiki/Sasadu"},

        { id: "32",
        housename: "Kambik",
        provincename: "Papua Barat Daya",
        img: "https://ideas.or.id/wp-content/themes/consultix/images/no-image-found-360x250.png",
        video: "",
        description: "Kambik adalah rumah adat yang dijadikan sebagai tempat penyelenggaraan pendidikan adat Suku Moi. Pendidikan adat tersebut merupakan pendidikan yang diselenggarakan sebelum masuknya agama Kristen ke tanah Malamoi. Para pemuda Moi dididik untuk menjadi anggota dewan adat atau pemimpin adat.",
        link: "https://id.wikipedia.org/wiki/Kambik"},

        { id: "33",
        housename: "Kaki Seribu",
        provincename: "Papua Barat",
        img: "https://phinemo.com/wp-content/uploads/2018/10/1-144.jpg",
        video: "https://www.youtube.com/watch?v=nJk2wtgB-5U",
        description: "Rumah kaki seribu atau Mod Aki Aksa adalah rumah adat asli dari penduduk suku Arfak yang menetap di Kabupaten Manokwari, Papua Barat. Rumah adat tersebut dijuluki demikian karena menggunakan banyak tiang penyangga di bawahnya, sehingga jika dilihat memiliki banyak kaki seperti hewan kaki seribu. Sedangkan untuk bagian atapnya dibuat dari daun jerami atau daun sagu.",
        link: "https://id.wikipedia.org/wiki/Rumah_kaki_seribu"},

        { id: "34",
        housename: "Yamewa",
        provincename: "Papua Tengah",
        img: "https://3.bp.blogspot.com/-E4qPzZdqyFo/WRCO5JVknDI/AAAAAAAAAcg/VPcTHIbs41cbWDTG550c8oObIKgBiLx4gCLcB/s1600/images%2B%25289%2529.jpg",
        video: "",
        description: "Rumah Yamewa adalah rumah adat suku Dani di Papua. Dibangun dengan kayu dan jerami, rumah ini mencerminkan gaya hidup dan tradisi masyarakat Dani.",
        link: ""},

        { id: "35",
        housename: "Kariwari",
        provincename: "Papua",
        img: "https://www.ruparupa.com/blog/wp-content/uploads/2022/02/Rumah-Adat-Kariwari.jpg",
        video: "https://www.youtube.com/watch?v=BY-RRKaVRpM",
        description: "Kariwari adalah salah satu rumah adat khas Papua, yakni rumah adat masyarakat Tobati-Enggros yang bermukim di sekitar Teluk Youtefa dan Danau Sentani, Jayapura. Berbeda dengan bentuk rumah adat Papua lainnya — seperti honai yang berbentuk bulat — rumah Kariwari berbentuk limas segi delapan. Rumah Kariwari biasanya terbuat dari, bambu, kayu besi dan daun sagu hutan. Rumah Kariwari terdiri dari dua lantai dan tiga kamar atau tiga ruangan, dengan fungsi yang masing-masing berbeda.",
        link: "https://id.wikipedia.org/wiki/Rumah_Kariwari"},

        { id: "36",
        housename: "Honai",
        provincename: "Papua Pegunungan",
        img: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Honai_House_Papua.jpg/1280px-Honai_House_Papua.jpg",
        video: "https://www.youtube.com/watch?v=zU6F7y2VLPc",
        description: "Honai atau onai merupakan rumah tradisional masyarakat Papua Pegunungan dan Papua Tengah khususnya suku Dani. Rumah honai berbentuk bulat sederhana dengan pintu kecil dan tidak dilengkapi jendela. Ada pula yang berbentuk persegi panjang, rumah jenis ini namanya Ebe'ai (Honai Perempuan). Tinggi rumah sekitar 2,5 meter yang terbagi menjadi dua bagian yaitu lantai bawah dan lantai atas. Lantai bawah biasa digunakan untuk tidur, sedangkan lantai atas digunakan untuk menjalankan aktivitas sehari-hari seperti makan, bersantai dan membuat kerajinan. Pada lantai bawah, dibagian tengah terdapat hipere yaitu tempat api unggun yang dipergunakan untuk memasak atau sekadar menghangatkan tubuh.",
        link: "https://id.wikipedia.org/wiki/Rumah_Honai"},

        { id: "37",
        housename: "Jew",
        provincename: "Papua Selatan",
        img: "https://upload.wikimedia.org/wikipedia/commons/1/13/Syuru_Ceremonial_House_%2848276841927%29.jpg",
        video: "https://www.youtube.com/watch?v=cxe4P1uis1I",
        description: "Rumah Jew atau dikenal sebagai Rumah Bujang merupakan salah satu rumah adat yang berasal dari Suku Asmat, khususnya dari ibu kota provinsi Papua yaitu Agats. Rumah Jew yang memiliki beberapa nama lain yaitu Je, Jeu, Yeu, atau Yai ini merupakan rumah panggung berbentuk persegi panjang yang terbuat dari kayu dan dinding beserta atapnya terbuat dari daun pohon sagu atau pohon nipah yang telah dianyam.",
        link: "https://id.wikipedia.org/wiki/Rumah_Jew"},
    ]
};